### ISSUE TITLE
`JSON readtable error` when creating a gist

### ISSUE THREAD

**Issue by darthdeus** [defunkt/gist.el#50]
After a completely clean install of `gist.el` into a new clean `~/.emacs.d` I get the following error when executing `(gist-buffer)`

```
Contacting host: api.github.com:443
if: JSON readtable error
```

**Comment by prathamesh-sonpatki** [comment]
I was also getting same error. I removed Github username and auth token from `.gitconfig` file and next time when I ran `gist-list`, it asked again for Github username & password. But after that everything worked.

**Comment by whatyouhide** [comment]
I did everything mentioned in this issue but I'm still getting the `JSON readtable error`. I consistently used tabs in my `~/.gitconfig`. When I call `M-x gist-list`, it asks for my username and my password but then stores my username **and my password** in `~/.gitconfig` (no tokens anywhere).

I don't have 2FA enabled. This error appears whatever gist.el command I use.

**Comment by ericychoi** [comment]
This was happening for me now.   Funny thing is it used to work fine, only recently it started breaking.  Maybe a recent API update on github side?

**Comment by ericychoi** [comment]
I have 2FA enabled.

**Comment by rgrinberg** [comment]
Also happening to me.

**Comment by jkrmr** [comment]
One weird trick to fix this

- [ ] Ensured my `.gitconfig` used [leading tabs instead of spaces](https://github.com/defunkt/gist.el/issues/50#issuecomment-44776899)
- [ ] Ensured I had an up-to-date oauth token in my gitconfig under [`github.token`, `github.oauth_token`, and `github.password`](https://github.com/sigma/gh.el/issues/28)
- [ ]  Ensured my `url-privacy-level` [wasn't set to `paranoid` or a list containing `agent`](https://github.com/sigma/gh.el/issues/28)
- [ ] [Manually typed my password](https://github.com/defunkt/gist.el/issues/29#issuecomment-5030279) when prompted instead of pasting it
- [ ] Killed and restarted the emacs daemon

Worked like a charm! 💯

**Comment by DinoChiesa** [comment]
I am also getting the dreaded "JSON readtable error" message, when i run gist-list.  This used to work. I have set my Personal Access Tokens, and am debugging the gh-url.el code, and I can see the token is being sent in the appropriate header. This is in gh-url-run-request  .  When I look at the return response from api.github.com, this is what I see: 

`
HTTP/1.0 403 Forbidden
Cache-Control: no-cache
Connection: close
Content-Type: text/html

Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.
closed
` 

It turns out I had an advice that was setting url-user-agent to nil.  This was making the github API unhappy.  Removing that  advice allowed everything to proceed.

**Comment by sigma** [comment]
interesting. I'll definitely update gh.el to ensure `url-privacy-level` and `url-user-agent` are locally set to acceptable values. Thanks so much for sharing !
